// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ZenLogAPI.Infra.Data.AppData;

#nullable disable

namespace ZenLogAPI.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZenLogAPI.Domain.Entities.ColaboradorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NumeroMatricula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex(new[] { "Cpf" }, "IDX_colaborador_cpf");

                    b.HasIndex(new[] { "Email" }, "IDX_colaborador_email");

                    b.HasIndex(new[] { "NumeroMatricula" }, "IDX_colaborador_matricula");

                    b.ToTable("tb_zlg_colaborador");
                });

            modelBuilder.Entity("ZenLogAPI.Domain.Entities.EmpresaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("Setor")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("tb_zlg_empresa");
                });

            modelBuilder.Entity("ZenLogAPI.Domain.Entities.LogEmocionalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DescricaoSentimento")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FezExercicios")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("HorasDescanso")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("LitrosAgua")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NivelEmocional")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("tb_zlg_log_emocional");
                });

            modelBuilder.Entity("ZenLogAPI.Domain.Entities.ColaboradorEntity", b =>
                {
                    b.HasOne("ZenLogAPI.Domain.Entities.EmpresaEntity", "Empresa")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ZenLogAPI.Domain.Entities.LogEmocionalEntity", b =>
                {
                    b.HasOne("ZenLogAPI.Domain.Entities.ColaboradorEntity", "Colaborador")
                        .WithMany("LogsEmocionais")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("ZenLogAPI.Domain.Entities.ColaboradorEntity", b =>
                {
                    b.Navigation("LogsEmocionais");
                });

            modelBuilder.Entity("ZenLogAPI.Domain.Entities.EmpresaEntity", b =>
                {
                    b.Navigation("Colaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
